#pragma once

#include <iostream>
#include <fstream>
#include <cmath>
#include <queue>
#include <map>
#include <sstream>
#include <assert.h> 
#include <float.h>
#include <cstdint>
#include <tuple>
#include "common.h"
#include "../GfxCore/bitmap.h"
#include "../GfxCore/color.h"
#include "../GfxCore/mathVector.h"
#include "../GfxCore/matrix.h"
#include "../GfxCore/meshIO.h"
#include "rasterLib.h"
#include "geom.h"
#include "resourceManager.h"
#include "camera.h"